project:
  type: book
  output-dir: _book

book:
  title: "Biol 4315: Genomics and Transcriptomics Lab Manual"
  author: "Instructor"
  cover-image: assets/cover.png
  chapters:
    - index.qmd
    - lab1/01-lab1.qmd
    - lab2_3/02-lab2.qmd
    - lab2_3/03-lab3.qmd
    - lab4/04-lab4.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 6
    number-sections: true
execute:
  eval: true          
  echo: true          
  warning: false      # Silences R/Bash warnings globally
  message: false      # Silences R messages (like 'Loading tidyverse')
  error: true
